import type { NextPage } from "next";
import Head from "next/head";
import { PersonnelUnitsLosses } from '../components/PersonnelUnitsLosses';
import { gethDate } from '../utils/helpers';
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.statistic.russianWarship.useQuery();

  if (!hello.data) {
    return <div>Loading...</div>;
  }

  console.log('====', hello.data?.data)

  const { date, day, increase, stats } =  hello.data?.data;

  const today = gethDate(date)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-[#e1d798] md:text-[5rem]">
          Personnel losses
        </h1>
        <p className="text-2xl text-[#e1d798]">{`Enemy personnel losses on ${today}, ${day}rd day of full-scale invasion`}</p>

        <PersonnelUnitsLosses increasePersonnelUnits={increase.personnel_units} personnelUnitsLosses={stats.personnel_units} />

        <div className="mt-3 grid gap-3 pt-3 text-center md:grid-cols-2 lg:w-2/3"></div>

      </main>
    </>
  );
};

export default Home;
